stages:
  - test

test:lint:
  stage: test
  script:
    - yarn install
    - yarn lint
  tags:
    - docker
  only:
    - merge_requests
  cache:
    paths:
      - node_modules/

test:audit:
  stage: test
  script:
    - yarn install
    - yarn run audit
  tags:
    - docker
  only:
    - merge_requests
  cache:
    paths:
      - node_modules/
